FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "raylib-aseprite-beef"
TargetType = "BeefLib"
StartupObject = "RaylibAsepriteBeef.Program"
DefaultNamespace = "RaylibAsepriteBeef"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/lib/$(Platform)/raylib-aseprite.lib"]
